esphome:
  name: "power-display-esphome"
# Enable the preferences library
  libraries:
    - Preferences

  includes:
    - power_display.h  

# Save values before shutting down
  on_shutdown:
    then:
      lambda: |-
        SaveValuesToNVM ();
        return;

esp32:
  board: esp32dev
  framework:
    type: arduino


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 60s

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Power-Display Fallback Hotspot"
    password: !secret fallback_password

time:
  - platform: homeassistant
    id: homeassistant_time

font: 
  # gfonts://family[@weight]
  - file: "gfonts://Mukta@700"
    id: large_text
    size: 38
    glyphs:
      ['&', '@', '!', ',', '.', '"', '%', '(', ')', '+', '-', '_', ':', '°', '0',
       '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E',
       'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
       'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 'd', 'e', 'f',
       'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
       'u', 'v', 'w', 'x', 'y', 'z','å', 'ä', 'ö', '/']    

  # gfonts://family[@weight]
  - file: "gfonts://Roboto@400"
    id: energy_text
    size: 18

  # gfonts://family[@weight]
  - file: "gfonts://Roboto@400"
    id: price_text
    size: 22

  # gfonts://family[@weight]
  - file: "gfonts://Source+Sans+Pro@400"
    id: small_text
    size: 10

color:
  - id: my_grey
    red: 30%
    green: 30%
    blue: 30%
    white: 50%

  # #800000
  # 128,0,0
  - id: COLOR_CSS_MAROON
    red:   0.5020
    green: 0.0000
    blue:  0.0000
    white: 0.0000

  # #ff0000
  # 255,0,0
  - id: COLOR_CSS_RED
    red:   1.0000
    green: 0.0000
    blue:  0.0000
    white: 0.0000

  # #ffa500
  # 255,165,0
  - id: COLOR_CSS_ORANGE
    red:   1.0000
    green: 0.6471
    blue:  0.0000
    white: 0.0000


  # #adff2f
  # 173,255,47
  - id: COLOR_CSS_GREENYELLOW
    red:   0.6784
    green: 1.0000
    blue:  0.1843
    white: 0.0000

  # #008000
  # 0,128,0
  - id: COLOR_CSS_GREEN
    red:   0.0000
    green: 0.5020
    blue:  0.0000
    white: 0.0000

  # #006400
  # 0,100,0
  - id: COLOR_CSS_DARKGREEN
    red:   0.0000
    green: 0.3922
    blue:  0.0000
    white: 0.0000

  # #f5f5f5
  # 245,245,245
  - id: COLOR_CSS_WHITESMOKE
    red:   0.9608
    green: 0.9608
    blue:  0.9608
    white: 0.0000

# "Icons made by Freepik from www.flaticon.com"
image:
  - file: "solar_energy32.png"
    id: solar_power
    type: RGB24
    #resize: 32x32
  - file: "electrical_tower32.png"
    id: grid_power
    type: RGB24
    #resize: 32x32

# Define sensors in HomeAssistant that we use for display
sensor:
  # Current import (unit is W - if you meter is using kW then it needs conversion)
  - platform: homeassistant
    id: import_el
    entity_id: sensor.momentary_active_import

  # Current export (if having solar production or similar, otherwise comment this out)    
  - platform: homeassistant
    id: export_el
    entity_id: sensor.momentary_active_export

  # Electricity prices from NordPool. Expecting Home Assistant NordPool Integration. https://github.com/custom-components/nordpool
  - platform: homeassistant
    id: nordpool_max  
    entity_id: sensor.nordpool
    attribute: max

  # // From NordPool, but you can also use Tibber etc.
  - platform: homeassistant
    id: price_now
    entity_id: sensor.electricity_price_langhallagatan_51b

  # Utility meter template in HomeAssistant. See example below (goes into configuration.yaml in HA.)  
  - platform: homeassistant
    id: consumption_today
    entity_id: sensor.forbrukning_huset_per_dag

  # Example:
  # utility_meter:
  # produktion_huset_per_dag:
  #   source: sensor.cumulative_active_export
  #   cycle: daily
  

text_sensor:
  - platform: homeassistant   # Nordpool
    id: nordpool_today
    entity_id: sensor.nordpool
    attribute: today
  - platform: homeassistant   # Nordpool
    id: nordpool_tomorrow
    entity_id: sensor.nordpool
    attribute: tomorrow

spi:
  clk_pin: 26 #SCL
  mosi_pin: 27 #SDA

display:
  - platform: ili9341
    model: TFT 2.4
    cs_pin: 13
    dc_pin: 14
    led_pin: 25  ### see note below ###
    reset_pin: 33
    rotation: 180
    update_interval: 10s

    lambda: |-

     auto powerDisplay = new PowerDisplay();
  
     // Unit is W - if your meter is reporting kW then it needs conversion (multiply value by 1000)
     powerDisplay->SetCurrentPower((id(import_el).state-id(export_el).state));  // Use if using solar production
     //powerDisplay->SetCurrentPower((id(import_el).state);                     // Use if not using any solar production

     powerDisplay->SetCurrentPrice(id(price_now).state);
     powerDisplay->SetTodayMaxPrice(id(nordpool_max).state);
     powerDisplay->SetTodaysPrices(id(nordpool_today).state.c_str());
     powerDisplay->SetTomorrowsPrices(id(nordpool_tomorrow).state.c_str());
     powerDisplay->WriteDailyEnergy(id(consumption_today).state);
     powerDisplay->DisplayIcons(&it, 10, 10 );  
     powerDisplay->WritePowerText(&it, 120, 40 );
     powerDisplay->WriteDailyAmount(&it, 120, 75, id(COLOR_CSS_WHITESMOKE));
     powerDisplay->CreateGraph(&it, 15, 115, 220, 100, my_grey);
     powerDisplay->SetGraphScale(0, 24, 0 );
     powerDisplay->SetGraphGrid(&it, 0, 2, 0, 1, my_grey);
     powerDisplay->WriteTimeLine(&it, id(homeassistant_time).now().hour, id(homeassistant_time).now().minute, id(COLOR_CSS_WHITESMOKE));
     powerDisplay->SetPrices("today");
     powerDisplay->SetPrices("tomorrow");
     powerDisplay->DrawPriceGraph(&it);
     powerDisplay->WritePriceText(&it, 120, 297 );

# Save global values every 1 minute. This is to quickly resume from a reboot and retain calculated values.
interval:
  - interval: 60s
    then:
      - lambda: |-
          SaveValuesToNVM();
    
captive_portal:
    